- name: stop acala service
  systemd:
    name: acala.service
    state: stopped

- name: purge chain
  shell: |
    set -o pipefail
    /usr/local/bin/acala purge-chain -y
  become: yes
  become_user: acala
  args:
    executable: /bin/bash
  changed_when: False

- name: start acala service
  systemd:
    name: acala.service
    state: started
